# de_en.yaml
save_data: system_data
## Where the vocab(s) will be written
src_vocab: system_data.vocab.src
tgt_vocab: system_data.vocab.tgt

# Corpus opts:
data:
    training:
        path_src: trainDataDe.txt
        path_tgt: trainDataEn.txt
    valid:
        path_src: valDataDe.txt
        path_tgt: valDataEn.txt

### Transform related opts:
#### Subword (None below because we manualy did this earlier)
#### Filter (None below)

# silently ignore empty lines in the data
skip_empty_level: silent

# General opts
save_model: foo
save_checkpoint_steps: 1000 #Was 10000
valid_steps: 1000 #Was originally 1000
train_steps: 5000 #Was 200000. Training speed seems to be able to handle a bit under 100000 per day... try 90000 total after FT?

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 4
gpu_ranks: [0, 1, 2, 3]
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]